workspace 'MobileMetricaSample.xcworkspace'
xcodeproj 'MobileMetricaSample.xcodeproj'
platform :ios, :deployment_target => '5.0'

target :MobileMetricaSample do
	xcodeproj 'MobileMetricaSample.xcodeproj' 
	pod 'KSCrash', :podspec=>'https://raw.github.com/kstenerud/KSCrash/master/KSCrash.podspec'  
	pod 'YandexMobileMetrica', :podspec=>'https://raw.github.com/yandexmobile/metrica-sdk-ios/master/YandexMobileMetrica.podspec'
end
